daangn/stackflow

.changeset/smart-students-visit.md
packages/navigator/src/components/Card.css.ts
packages/navigator/src/components/Navbar.css.ts

Co-authored-by: Hyeseong Kim <tim@daangn.com>

fix navbar styles

---

.changeset/friendly-dragons-shave.md
.changeset/silver-files-reflect.md
packages/navigator/CHANGELOG.md
packages/navigator/package.json
packages/plugin/CHANGELOG.md
packages/plugin/package.json
yarn.lock

- Bump @karrotframe/navigator version to v0.21.0
- Bump @karrotframe/plugin version to v0.3.0

Bump version 

---

.prettierignore
packages/navigator/CHANGELOG.md
packages/navigator/package.json
packages/navigator/src/components/Card.css.ts
packages/navigator/src/components/Card.tsx

- Support animate option for route event from android theme too

fix(navigator): support animate option for android theme

---

extensions/basic-ui/src/AppScreen.css.ts
extensions/basic-ui/src/AppScreen.tsx

- 빨리 여러번 Pop 했을때 하얀 화면이 안보이도록 처리
- offset이 정상적으로 작동하지 않는 문제가 있는데 해결하기 쉽지 않아서, 다른 PR로 만들게요.

fix(basic-ui): fix multiple pop behavior

---

extensions/basic-ui/src/utils/useSwipeBack.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx

- using hash router by `useHash` option. (default: browser router)
- so stackflow can support `file://`
https://user-images.githubusercontent.com/20325202/175483147-3771b357-79db-4560-963d-c94a022a69a7.mov

feat(plugin-history-sync): add useHash option in historySyncPlugin()

---

extensions/basic-ui/src/AppBar.css.ts
extensions/basic-ui/src/AppBar.tsx
extensions/basic-ui/src/AppScreen.css.ts
extensions/basic-ui/src/AppScreen.tsx

```html
<html data-stackflow-basic-ui-theme="cupertino">
</html>
```
SSG나 SSR 환경에서 [FOUC](https://ko.wikipedia.org/wiki/FOUC) 현상 제거. Inspired by `@seed-design/stylesheet`

feat(basic-ui): support theme in SSG

---

LICENSE
core/package.json
demo/package.json
docs/package.json
extensions/basic-ui/package.json
extensions/plugin-history-sync/package.json
extensions/plugin-renderer-basic/package.json
integrations/react/package.json
package.json
packages/esbuild-config/package.json

chore: Apache-2.0 to MIT

---

extensions/plugin-history-sync/src/historySyncPlugin.tsx

fix(plugin-history-sync) path resolve issue when `useHash: true`

---

extensions/basic-ui/src/AppBar.tsx
extensions/basic-ui/src/AppScreen.tsx

* basic-ui:  `<AppScreen appBar={{ height: "70px" }}/>` 다음과 같이 `AppBar`의 height 설정을 할 수 있게 추가하였습니다.

feat(basic-ui): AppBar custom height

---

extensions/basic-ui/src/AppBar.css.ts
extensions/basic-ui/src/styles/f.css.ts

CSS에서
```css
* {
box-sizing: border-box;
}
```
속성이 걸렸을때 문제를 해결합니다.
cc. @mooyoul

fix(basic-ui): fix when `* { box-sizing: border-box; }`

---

README.md

Fixed license Apache 2.0 to MIT in `README.md`

docs: update license

---

extensions/basic-ui/src/AppScreen.css.ts
extensions/basic-ui/src/AppScreen.tsx

Fixed: #214 
`paper`에서 `edge`를 뺀 후 `z-index` 값을 주고 `appscreen` 밑으로 넣었어요.
`appscreen`의 children을 하나로 감쌀 때, 안 감쌀 때나 `position` 유무에 따라 다 테스트해봤어욥

fix(@stackflow/basic-ui): cover edge full height

---

docs/theme.config.js

docs: fix license

---

examples/spec/src/components/_pages/PageTabs.tsx
packages/tabs/src/Tabs.tsx

1. 탭 유형(useInlineButtons)이 동적으로 수정될 때 TabBar style이 깨지는 문제
2. 탭 유형이 useInlineButtons 일 때, 화면 밖의 탭으로 활성화 된 탭이 표시되면 탭이 보이지 않는 문제

fix(tabs): Activation tab is not visible and tab bar style breaking when tab type is changed dynamically

---

core/src/aggregate.spec.ts
core/src/aggregate.ts
core/src/event-types/PushedEvent.ts
core/src/event-types/ReplacedEvent.ts
core/src/event-utils/filterEvents.spec.ts
core/src/event-utils/validateEvents.spec.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx
extensions/plugin-preload/src/pluginPreload.tsx
integrations/react/src/core/CoreProvider.tsx
integrations/react/src/useActions.ts

- Pushed, Replaced Event에 `params` 필드가 모호해서, `activityParams`로 바꿨어요~

refactor(core): rename params -> activityParams

---

.github/workflows/build.yml
.github/workflows/integration.yml

https://github.com/daangn/stackflow/pull/246#issuecomment-1286539432
이번에 `basic-ui` => `plugin-basic-ui`로 이름 바뀌면서 PR 테스트가 실패하는 것 같네요 .. !!

chore(plugin-basic-ui): github actions

---

extensions/plugin-basic-ui/src/components/AppScreen.tsx

fix(plugin-basic-ui): disable `useLazy` when `enter-done`

---

.pnp.cjs
extensions/plugin-renderer-web/README.md
extensions/plugin-renderer-web/esbuild.config.js
extensions/plugin-renderer-web/package.json
extensions/plugin-renderer-web/src/index.ts
extensions/plugin-renderer-web/src/webRendererPlugin.tsx
extensions/plugin-renderer-web/tsconfig.json
yarn.lock

- 대부분의 코드는 plugin-renderer-basic 코드와 동일해요.
- 데스크탑 브라우저 환경에서 최신 하나의 activity만 render할 수 있도록 코드를 조금 수정해서 plugin을 추가했어요.
- 자체 프로젝트에 추가하려다가 stackflow에 있으면 좋을까 싶어서 추가해봤어요. 의견 부탁드려요.

feat(plugins): Add plugin-renderer-web

---

extensions/plugin-stack-depth-change/README.md

- Update README to be more suitable for such extension

docs: update README

---

integrations/react/src/stackflow.tsx

This lets plugin authors expose an interface for including multiple plugins at once.

feat: support infinitely nested plugins array

---

docs/pages/guided-tour/activity.ko.mdx

chore(docs): fix code example typo

---

extensions/plugin-basic-ui/src/components/AppScreen.tsx

- `<AppScreen />` 컴포넌트에 `preventSwipeBack` 옵션을 추가합니다

feat(plugin-basic-ui): preventSwipeBack

---

.github/workflows/build.yml
.github/workflows/integration.yml
core/src/Effect.ts
core/src/Stack.ts
core/src/aggregate.spec.ts
core/src/aggregate.ts
core/src/createCoreStore.ts
core/src/index.ts
core/src/interfaces/StackflowActions.ts
core/src/produceEffects.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx
integrations/react/src/BaseActivities.ts
integrations/react/src/MainRenderer.tsx
integrations/react/src/PluginRenderer.tsx
integrations/react/src/StackflowReactPlugin.ts
integrations/react/src/core/CoreProvider.tsx
integrations/react/src/stack/StackProvider.tsx
integrations/react/src/stackflow.tsx
integrations/react/src/utils/createRef.ts
integrations/react/src/utils/index.ts

- `AggregateOutput` 타입명을 `Stack`으로 변경합니다.
- 정의를 다음과 같이 재구성해요: `aggregate()` 함수는 `DomainEvent[]`를 받아서 `Stack`을 내보내는 함수
- 기존에 Ultra Cache가 작동하지 않던 부분을 CI에 추가해요.
Close #292

feat(react): addActivity, addPlugin

---

core/src/produceEffects.spec.ts
core/src/produceEffects.ts

- `replace()` 시에 `PoppedEffect`가 발생하는것을 고쳐요.

fix(core): double effect triggering when ReplacedEvent

---

core/src/produceEffects.spec.ts
core/src/produceEffects.ts

- 요 건은 간단한 픽스라서 0.19.1로 배포할까 싶어요. (fix)

fix(core): omit `isRoot`

---

docs/pages/guided-tour/navigating.ko.mdx

- 예시인 Article 컴포넌트의 export 문의 컴포넌트가 MyActivity 였던 부분을 수정해요

fix(docs): navigating

---

docs/pages/guided-tour/state.ko.mdx

docs: fix typo

---

extensions/plugin-basic-ui/src/components/AppScreen.tsx
extensions/plugin-basic-ui/src/components/BottomSheet.tsx
extensions/plugin-basic-ui/src/components/Modal.tsx
extensions/plugin-basic-ui/src/index.ts

- `useAppScreen()`을 통해 `<AppScreen />`에서 제공하는 각종 dispatcher들에 접근하도록 오픈
- 현재는 `scroll()` 함수 하나 노출

feat(plugin-basic-ui): `useAppScreen()`

---

extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppScreen.css.ts
extensions/plugin-basic-ui/src/components/BottomSheet.css.ts
extensions/plugin-basic-ui/src/components/Modal.css.ts
extensions/plugin-basic-ui/src/hooks/useStyleEffectOffset.ts
extensions/plugin-basic-ui/src/hooks/useStyleEffectSwipeBack.ts

- add `will-change` property
- change `translateX`, `translateY` to `translate3d`

feat(plugin-basic-ui): animation performance optimization

---

.github/workflows/build.yml
.github/workflows/integration.yml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Replaced third-party actions with official cache actions([Restore action](https://github.com/actions/cache/blob/main/restore/README.md), [Save action](https://github.com/actions/cache/blob/main/save/README.md)).
- [actions/cache#1035](https://github.com/actions/cache/pull/1035)

chore: replace with official cache actions

---

integrations/react/src/useEnterDoneEffect.ts

- export default로 되어있던걸 export로 수정했어요 😭

fix(react): useEnterDoneEffect

---

extensions/plugin-basic-ui/src/components/AppScreen.tsx

fix(plugin-basic-ui): android theme appBar zIndex fix

---

extensions/plugin-basic-ui/src/hooks/useStyleEffect.ts
extensions/plugin-basic-ui/src/hooks/useStyleEffectHide.ts
extensions/plugin-basic-ui/src/hooks/useStyleEffectOffset.ts
extensions/plugin-basic-ui/src/hooks/useStyleEffectSwipeBack.ts
integrations/react/src/useActiveEffect.ts
integrations/react/src/useEnterDoneEffect.ts
integrations/react/src/utils/index.ts
integrations/react/src/utils/noop.ts

refactor: Export noop and use it

---

integrations/react/src/stackflow.tsx
integrations/react/src/useActions.ts

- Function Overloading을 통해 Breaking Changes를 일으키지 않습니다.

feat(react): add `pop(n)` interface

---

extensions/plugin-basic-ui/src/basicUIPlugin.tsx

- Customize `plugin-basic-ui`'s option with `initialContext`
```typescript
<Stack initialContext={{ theme: "...", }} />
```
```typescript
stackflow({
// ...
plugins: [
basicUIPlugin(({ initialContext }) => ({
// ...
})),
],
})
```

feat(plugin-basic-ui): add function type options

---

.pnp.cjs
extensions/plugin-devtools/.eslintrc.js
extensions/plugin-devtools/README.md
extensions/plugin-devtools/esbuild.config.js
extensions/plugin-devtools/package.json
extensions/plugin-devtools/src/devtoolsPlugin.tsx
extensions/plugin-devtools/src/index.ts
extensions/plugin-devtools/tsconfig.json
yarn.lock

This plugin is used as a data storage layer for the Stackflow Devtools.

feat(devtools): add stackflow devtools plugin

---

.github/workflows/integration.yml

Filling in the missing work from #374

fix(ci): use typecheck instead of tsc

---

extensions/plugin-history-sync/src/historySyncPlugin.spec.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx

- test: add failing test cases
- fix: pop states before replacing activities
- fix: prevent root activity from popping

fix: fix history states when replacing or popping activity

---

extensions/plugin-history-sync/src/historyState.ts
extensions/plugin-history-sync/src/historySyncPlugin.spec.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx

- temp
- fix(plugin-history-sync): replace silent state into flags

fix(plugin-history-sync): replace silent state into flags

---

.changeset/mean-zebras-accept.md
extensions/plugin-basic-ui/src/index.ts

- Export css variables from basic ui components(`AppScreen`, `BottomSheet`, `Modal`)

feat(plugin-basic-ui): export css variables from components

---

docs/pages/guided-tour/activity.mdx

docs(guided-tour): `export` 키워드 추가

---

extensions/plugin-google-analytics-4/README.md
extensions/plugin-stack-depth-change/README.md

- docs(plugin-google-analytics-4): fix typo of plugin-google-analytics-4 README.md
- docs(plugin-stack-depth-change): fix typo of plugin-stack-depth-change README.md

docs: fix typos of README.md

---

.changeset/small-pears-cheat.md
extensions/plugin-history-sync/src/historySyncPlugin.tsx

- fix(plugin-history-sync): request history tick on init
- chore: bump package

fix(plugin-history-sync): request history tick on init

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/release.yml

- update action version
- normalize cache path
- improve cache key

chore: improve ci

---

.changeset/chilly-toys-cheer.md
docs/pages/api-references/future-api/api-pipelining.en.mdx
docs/pages/api-references/future-api/api-pipelining.ko.mdx
docs/pages/api-references/future-api/changes.en.mdx
docs/pages/api-references/future-api/loader-api.en.mdx
docs/pages/api-references/future-api/loader-api.ko.mdx

Fixed documentation to match new `ActivityDefinition` field type
* [`docs/pages/api-references/future-api/api-pipelining.en.mdx`](diffhunk://#diff-fbfcab5142ca63b4e19db4e90a7d831c8aded2126f948f39c3389a0c4775d667L17-R17): Changed `path` to `route` in the `makeTemplate` function call within the `main` function.
* [`docs/pages/api-references/future-api/api-pipelining.ko.mdx`](diffhunk://#diff-94858f2ae2c62df3abefbfa3fb235c04680dc74db457b87ff07dc56fc745576eL17-R17): Changed `path` to `route` in the `makeTemplate` function call within the `main` function.
* [`docs/pages/api-references/future-api/changes.en.mdx`](diffhunk://#diff-d9bd61d81697cd1d8cc9805b7181f3ca38abcaf9aeeffa084d2351a816d6ec39L48-R64): Replaced `path` with `route` in the `config` object and added a new activity with a nested …

fix(docs): update `path` to `route` in future API documentation

---

.changeset/chilled-hats-love.md
.changeset/chilly-toys-cheer.md
.changeset/green-dolphins-sneeze.md
.changeset/plenty-stingrays-knock.md
.changeset/popular-glasses-sing.md
core/CHANGELOG.md
core/package.json
docs/CHANGELOG.md
docs/package.json
extensions/plugin-basic-ui/CHANGELOG.md
extensions/plugin-basic-ui/package.json
integrations/react/CHANGELOG.md
integrations/react/package.json
yarn.lock

Revert "Version Packages"

---

.changeset/big-eyes-raise.md
docs/pages/docs/get-started/activity.en.mdx
docs/pages/docs/get-started/activity.ko.mdx

https://stackflow.so/docs/get-started/activity
basicUiPlugin import 가 빠져있어서 추가하였습니다

fix(docs): add import basicUiPlugin

---

.changeset/funny-melons-drum.md
.pnp.cjs
integrations/react/package.json
yarn.lock

fix(react): remove unused dependencies
