daangn/stackflow

packages/karrotframe/src/navigator/Navigator.tsx

[React Transition Group](http://reactcommunity.org/react-transition-group/transition-group#TransitionGroup-props)
- karrotframe 내부 [Navigator.tsx#L400](https://github.com/daangn/karrotframe/blob/master/packages/karrotframe/src/navigator/Navigator.tsx#L400)에서 [react-transition-group](https://www.npmjs.com/package/react-transition-group)을 사용하는데 react-transition-group 문서(위 사진)에서 확인할 수 있듯이 `<TransitionGroup />` 컴포넌트는 default `<div />`로 렌더링 된다고 하며, 의도치 않게 css style을 망가뜨릴 수 있다고 합니다.
가이드를 따라 component props에 `null`을 주어 안쓰이는 `div` 엘리먼트를 제거하였습니다.

fix(karrotframe): remove useless div element in TransitionGroup

---

packages/karrotframe/src/navigator/components/Card.scss
packages/karrotframe/src/navigator/components/Card.tsx

https://github.com/daangn/karrotframe/issues/53#issuecomment-817242268
[keen-slider](https://keen-slider.io/)를 같이 사용하게 될 경우 keen-slider가 제대로 동작하지 않는 이슈가 있습니다. 추후 다른 라이브러리와 함께 사용할 때도 비슷한 이슈가 있을 것 같아 css 속성을 수정하였습니다.
- `display: none`을 하면 내부 엘리먼트까지 영향을 미치게 되므로 `<ScreenHelmet />` 렌더링 타이밍 이슈를 해결하기 위한 용도와 동일하게 `visiblity: hidden`으로 수정하였습니다.
- Card.tsx 내부 코드 중 `props.isRoot`가 loading state의 initial state인데, [Card.tsx#L176](https://github.com/daangn/karrotframe/blob/master/packages/karrotframe/src/navigator/components/Card.tsx#L176)의 경우 root가 false이면 loading도 false, 따라서 [Card.tsx#L180](https://github.com/daangn/karrotframe/blob/master/packages/karrotframe/src/navigator/components/Card.tsx#L180) 줄의 코드가 의미가 없다고 판단하여 scss 등 불필요한 코드를 삭제하였습니다.

fix(karrotframe): change display: none to visiblity: hidden in isLoading

---

packages/tabs/README.md

* `@karrotframe/tabs` 를 적용하다보니, 예시에 기재된 props 형태가 mismatch 나는 부분이 있어서 수정했어요.
* #89 에서 `render` -> `component` 로 변경되었던데, 이렇게 변경하실 예정인걸까요?

chore(tabs): Fix typo

---

.github/workflows/test.yml
packages/plugin/README.md
packages/plugin/package.json

Remove next methods below from api doucment:
- `preventPop`
- `preventPush`
- `preventReplace`
These methods would be supported soon with nextMethods too
- `activatePop`
- `activatePush`
- `activateReplace`

chore(plugin): Remove some methods of hook options that are not supported yet from document

---

packages/navigator/src/__tests__/plugin.test.tsx
packages/plugin/README.md
packages/plugin/src/basics/loggerMiddlewarePlugin.tsx

`executor` from NavigatorPluginType should return `PluginType` object.
But current name of function could remind of react hook like `useFoo`.
Current function is replaced with anonymous function to avoid such misconception.

Remove function like react hook for executor of plugin and Declare anonymous function as executor of plugin

---

packages/navigator/src/components/Card.css.ts
packages/navigator/src/components/Navbar.css.ts

- Dim have covered ScreenHelmet in iOS because Dim area did not consider safe-area.
```javascript
top: `calc(${vars.navbar.height} + env(safe-area-inset-top))` 
```
- With this css, margin space from Top area should be reserved with *`PLUS`* `safe-area-inset-top`

Reserve space for ScreenHelmet with env(safe-area-inset-top) option to push dim area downward

---

examples/spec/src/components/_pages/PageScreenHelmet.tsx
packages/navigator/README.md
packages/navigator/src/ScreenHelmet.tsx
packages/navigator/src/__tests__/ScreenHelmet.test.tsx
packages/navigator/src/components/Card.tsx
packages/navigator/src/components/Navbar.tsx
packages/navigator/src/components/Stack.ContextScreenHelmet.tsx

- add `visible` option into `ScreenHelmet` to control visibility for navbar
- `visible` option is passed `setScreenHelmetVisible` of `ScreenHelmet` when `ScreenHelmet` is mounted
- add `preventBackSwipe` option into `ScreenHelmet` to block swipe back action with `true` value
- `preventBackSwipe` is passed into dependencies of useEffect from `Card` because it should re-render to initialize `$edge` by `preventBackSwipe`

fix(navigator): Add visible option for ScreenHelmet and preventSwipeBack option

---

examples/spec/src/components/_pages/PageScreenHelmet.tsx
examples/with-cra/src/App.tsx
packages/navigator/README.md
packages/navigator/src/Navigator.tsx
packages/navigator/src/ScreenHelmet.tsx
packages/navigator/src/__tests__/Navigator.test.tsx
packages/navigator/src/__tests__/ScreenHelmet.test.tsx
packages/navigator/src/__tests__/plugin.test.tsx
packages/navigator/src/components/Card.tsx
packages/navigator/src/components/Navbar.tsx
packages/navigator/src/components/Stack.ContextScreenHelmet.tsx
packages/navigator/src/components/Stack.tsx

- Add `hideLeftButton` option to hide close button or back button
- This option would cover close button and back button both from left side of navbar, therefore this options get `hideLeftButton` instead of `hideCloseButton` or `hideBackButton`

fix(navigator): Add hideLeftButton option to hide back or close button from navbar

---

packages/navigator-plugin/src/types/navigator.ts
packages/navigator/src/components/Navbar.tsx

- expose hook to access ScreenHelmetProps when navbar is mounted and is unmounted
- ScreenHelmet is used to control metadata, but ScreenHelmet do also control navbar component. IMHO, mounting navbar is a point for plugin hook.
- But `beforeMountNavbar` is not supported yet. It should be discussed to check whether this hook is required and how to implement that.

feat: Support hook when navbar is mounted and unmounted

---

packages/navigator/src/Navigator.tsx
packages/navigator/src/Screen.tsx

- 'children' basic prop is removed in @types of React 18

fix(navigator): Declare children props explicitly [skip ci]

---

packages/navigator/src/Navigator.css.ts
packages/navigator/src/__tests__/ScreenHelmet.test.tsx
packages/navigator/src/__tests__/__snapshots__/ScreenHelmet.test.tsx.snap
packages/navigator/src/components/Card.css.ts
packages/navigator/src/components/Card.tsx
packages/navigator/src/components/Navbar.css.ts
packages/navigator/src/components/Navbar.tsx
packages/navigator/src/components/Stack.ContextScreenHelmet.tsx
packages/navigator/src/helpers/nextTick.ts
packages/navigator/src/hooks/index.ts
packages/navigator/src/hooks/useMounted.ts

https://user-images.githubusercontent.com/10165823/165315197-2408ff50-f665-4688-9351-4080056b8b82.MP4
- visible false 일 때 기존에는 컴포넌트를 언마운트했는데, 이제는 translateY 로 viewport 바깥으로 밀어내요. 무거운 컴포넌트가 아니기 때문에 언마운트가 아니어도 성능에 큰 차이가 없을거라고 생각해요.
- nextTick helper 함수 내부에서 setTimeout 을 사용해요. 기존에는 Promise.resolve 를 사용했어요.
- vanilla-extract 의 assignInlineVars 를 사용해서 vars.navbar.animationDuration 과 vars.navbar.translateY 를 다루어요.
- variant 를 추가하는 것이 더 복잡도를 늘린다고 판단하여 assignInlineVars 을 사용하기로 결정했어요
- 추후 animationDuration 을 option 으로 받아 동적으로 다룰 경우 수정이 용이해요
- 전체 코드에서 assignInlineVars 사용빈도가 아주 적기 때문에 사용을 지양하는 convention 이 따로 있거나, 스타일링 규칙을 따르지 않은 것이 아닐까 우려가 있어요.
- navbar 를 viewport 위로 밀어낼 때에는, 바로 뒤의 screen 이 나타나지 않도록 variant 를 이용해서 background 를 하얀색으로 칠해요. 
- vars.navbar.animationDuration 는 mounted 가 true 일 때 0 이외의 …

feat(navigator): navbar transition

---

packages/navigator/src/components/Card.css.ts
packages/navigator/src/components/Card.tsx

- android theme 일 때와 present 옵션이 true 인 경우에도 navbar on/off 에 따른 transition 을 지원해요
- transition 이 중첩되어 있을 때 하나의 transition 이 0 인 경우에는 다른 transition 에도 영향을 미쳐서 0 대신 1ms 로 변경했어요.

Support android theme and present option of push or pull call for navbar transition 

---

packages/navigator/src/components/Card.tsx
packages/navigator/src/components/Navbar.css.ts
packages/navigator/src/components/Navbar.tsx
packages/navigator/src/components/Stack.ContextScreenHelmet.tsx
packages/navigator/src/hooks/useMounted.ts

- navbar 가 기본값으로 항상 보이는, 의도치 않은 파괴적 변환이 있어서 다시 [packages/navigator/src/components/Stack.ContextScreenHelmet.tsx](https://github.com/daangn/karrotframe/compare/fix/set-default-false-for-navbar?expand=1#diff-14a6683ebfbc980fccf040e4508485b7952d3377660b55e432a54f7e6eff3ec6) 의 screenHelmetVisible state 의 초기값을 false 로 변경했어요
- safari 환경에서 처음 렌더링 할 때는 navbar 가 transition 효과를 발생시키지 않도록 하기 위해 다음과 같이 작업했어요.
- `useImperativeHandle` 을 사용해서 navbar.tsx 가 mounted 되었을 때 card.tsx 가 transition 이 가능한 상태가 되어요. 그래서 card.tsx 에서는 mounted 값 대신 activeTransition 라는 값으로 vars.navbar.animationDuration 을 설정해요.
- `useImperativeHandle` 을 사용하기 위해 navbar 를 `forwardRef` 로 감쌌어요(이거 때문에 PR 에서는 코드를 많이 수정한 것처럼 나오네요..)
- navbar.tsx 에서는 mounted 된 상태 이후에 translateY 값을 동적으로 설정하고, 그 이전에는 0으로 설정해서 transition 효과가 나타나지 않도록 변경했어요.
- ` …

fix(navigator): Make navbar not expose in default and modify transition condition for navbar

---

extensions/plugin-history-sync/src/historySyncPlugin.tsx

https://github.com/daangn/stackflow/issues/182
`parseState(getCurrentState())`부분 object deeps 안맞는 버그 수정

fix(history-sync-plugin): fix getCurrentState() type error

---

extensions/plugin-history-sync/src/historySyncPlugin.tsx

아래와 같이 Fallback URL을 Route 마다 넘겨줄 수 있도록 추가 구현했어요.
```typescript
stackflow({
plugins: [
historySyncPlugin({
routes: {
Something: [
"/something",
"/something2", // 여러개의 URL을 한 Activity에 등록 가능
]
}
// ...
})
],
})
```

feat(plugin-history-sync): fallback url interface and impl

---

demo/src/activities/Article.tsx
demo/src/activities/Main.tsx
integrations/react/src/MainRenderer.tsx
integrations/react/src/PluginRenderer.tsx
integrations/react/src/activity/ActivityComponentType.tsx

- `params` 필드로 액티비티 컴포넌트의 props를 한번 감쌉니다.
BREAKING CHANGES: 기존에 Props 인터페이스를 통해 Activity Params를 받아오던 부분에 파괴적 변환이 발생합니다.
CLOSE: #206

fix(react): Support reserved words(ref, key) in `activityParams`

---

.pnp.cjs
demo/package.json
extensions/compat-await-push/README.md
extensions/compat-await-push/esbuild.config.js
extensions/compat-await-push/package.json
extensions/compat-await-push/src/index.ts
extensions/compat-await-push/src/receive.ts
extensions/compat-await-push/src/resolveMap.ts
extensions/compat-await-push/src/send.ts
extensions/compat-await-push/tsconfig.json
integrations/react/src/useActions.ts
yarn.lock

기존에 Karrotframe에 존재하던 `await push()`, `pop().send()` 인터페이스를 모방한 Compat 라이브러리를 제공합니다.
```typescript
import { receive } from "@stackflow/compat-await-push";
const MyActivity = () => {
const { push } = useFlow();
const onClick = async () => {
const data = await receive(
push("NextActivity", {
// ...
}),
);
console.log(data);
};
};
```
```typescript
import { send } from "@stackflow/compat-await-push";
const NextActivity = () => {
const { id } = useActivity();
const { pop } = useFlow();
const onClick = async () => {
pop();
send({
activityId: id,
data: {
hello: "world",
},
});
};
};
```
`push()`, `replace()` 함수에서 새로 생성된 `activityId`를 반환합니다 (기존: `void`)

feat(compat-await-push): compat library for await push interface

---

extensions/basic-ui/src/AppBar.tsx

기존에 `customBackButton`, `customCloseButton`은 어떤걸 커스텀하는건지 모호했어요. 이 부분을 해결해요.
```tsx
// as-is
<AppScreen
customCloseButton={() => <IcBack />}
/>
// to-be
<AppScreen
closeButton={{
renderIcon: () => <IcBack />
}}
/>
```
```tsx
// as-is
<AppScreen
onClose={() => { ... })
/>
// to-be
<AppScreen
closeButton={{
onClick() { ... }
}}
/>
```
```tsx
// as-is
// 불가능
// to-be
<AppScreen
closeButton={{
render() { ... },
}}
/>
```

feat(basic-ui): backButton, closeButton

---

demo/src/stackflow.ts
integrations/react/src/StackRefManager.tsx
integrations/react/src/stackflow.tsx

- `stackRef`는 새로운 용어/멘탈모델이고, 불필요한 학습 장벽이 될 수 있습니다.
- 따라서 기존에 활용하던 `actions`라는 용어를 활용해 추상화합니다.

refactor(react): hide `stackRef` interface with actions

---

core/src/aggregate.spec.ts
core/src/aggregate.ts

- 액티비티 전환 효과 중에, 해당 액티비티 ID를 타겟으로한 ReplacedEvent가 일어나면, 애니메이션이 씹히는 이슈를 해결해요

feat(core): activity replacement transition is ignored when activity exists

---

extensions/plugin-basic-ui/src/basicUIPlugin.tsx

- When server-side rendered, className is not changed in hydration.
- So, `theme` option set in the Node.js environment is not changed in Browser environment

fix(plugin-basic-ui): when SSR, remove className in root div element

---

docs/pages/advanced/preloading.ko.mdx
extensions/link/README.md
extensions/link/src/createLinkComponent.tsx
extensions/link/src/index.ts

- 샘플 코드를 훑어보다가 `createLink()`보다는 `createLinkComponent()`라고 명시적으로 하는 편이 더 나은것같아서 이름을 수정했어요

refactor(link): rename `createLink` to `createLinkComponent`

---

extensions/plugin-preload/src/pluginPreload.tsx

- preloadPlugin을 사용하다보니 loaders를 다른 변수로 지정해두고 싶은 니즈가 있었어요.
- 그런데 options typing이 export가 안되어있어서 type을 제대로 잡을 수 없는 문제를 겪어서 해당 type을 export하면 좋겠다고 생각했어요.
- 아래와 같은 예시로 작성하고 싶다고 생각했어요. 혹시 불필요하다고 생각되시면 의견 부탁드려요!
```
const loaders: PreloadPluginOptions<TypeActivities> = {
....
}
stackflow({
....,
plugins: [
....,
preloadPlugin({ loaders }),
....,
]
}
```

chore(preload-plugin): Update pluginPreload to export option typing

---

extensions/plugin-history-sync/src/historySyncPlugin.tsx
integrations/react/src/core/useCoreActions.ts

- Activity Context가 Serialize되면서, `preloadRef` 내부의 인스턴스가 날아가는 문제가 발생
- 이를 해결하기 위해, Serialization 로직을 제거하고, `historySyncPlugin`에서 `history.state`를 set하는 부분에서 Activity Context를 제외

fix(react): preload with relay

---

extensions/plugin-renderer-web/src/webRendererPlugin.tsx

You can see the typo `webRednererPlugin` (notice `Re"dn"erer`) here.
https://github.com/daangn/stackflow/blob/1ded1f0617b25287576e499be639c74cab6328cd/extensions/plugin-renderer-web/src/webRendererPlugin.tsx#L4
I just fixed the typo.
This change would make a new breaking change here. Any package depends on `stackflow/plugin-renderer-web` will require to take action.

Fix typo on webRendererPlugin.tsx

---

docs/pages/_document.js

a 함수에 다음 코드를 추가하여 사용하는 OS 가 다크모드일 때 `class='dark'` 가 되도록 해서 다크모드를 지원해요
```
e.classList.remove("light");
e.classList.remove("dark");
pd.matches ? e.classList.add("dark") : e.classList.add("light");
```

fix(docs): Support Dark Mode

---

extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppBar.tsx
extensions/plugin-basic-ui/src/theme.css.ts

This change adds `backgroundColor` to AppBar prop
- AppBar's background-color can declaratively be set
- If no prop is passed, use `globalVars.backgroundColor` (for backward compatibility)

feat: add bg-color prop to appBar

---

core/src/index.ts
core/src/makeCoreStore.spec.ts
core/src/makeCoreStore.ts
integrations/react/src/core/CoreProvider.tsx
integrations/react/src/stackflow.tsx
integrations/react/src/utils/index.ts
integrations/react/src/utils/makeRef.ts

- 내부에서 사용하는 Object들의 초기화 함수를 `make*`로 통일해요.
- 기존에 `makeEvent` 등 대부분 통일되어 있었는데, 통일되지 않은 API들을 통일했어요.

refactor(core, react): `create*` to `make*`

---

integrations/react/src/stackflow.tsx

`store.init()`과 Activity 렌더링의 실행 순서를 보장합니다.

fix(react): init coreStore right after `makeCoreStore()`

---

integrations/react/src/index.ts
integrations/react/src/useEnterDoneEffect.ts

- activity가 올라왔지만 transition이 완료되지 않았을 때 keypad를 올리거나 animation을 발생시키면 layout이 깨지는 경우가 있어 activity가 위로 올라오고 transition이 완료되었을 때 수행하도록 하는 훅을 추가해줬어요.

feat(feat): useEnterDoneEffect

---

integrations/react/src/index.ts
integrations/react/src/useStep.ts

- 현재 step의 정보를 받아오는 훅을 만들었어요.
- activity가 처음 만들어질 때 activity가 step에 가장 먼저 들어가더라구요. 그런데 현재 step의 정보를 얻고 싶은 유저가 원하는 정보는 아닐 것 같아서 activity는 제외시켰어요.

feat(react): useStep

---

integrations/react/src/shims/index.ts
integrations/react/src/shims/useTransition.ts
integrations/react/src/useActions.ts
integrations/react/src/useStepActions.ts

- `useTransition` fallback을 `src/shims` 내 별도의 파일로 분리하고, 사용처에서 이를 사용하도록 변경했어요.

refactor(react): move `useTransition` shim to separate file

---

extensions/plugin-basic-ui/src/hooks/useStyleEffect.ts

제네릭을 사용해 any를 지우고 흩어져있던 타입들을 하나로 관리해요. ~~그리고 RefObject를 구체적으로 가져옵니다.~~

refactor(plugin-basic-ui): refobject using generics

---

extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppBar.tsx
extensions/plugin-basic-ui/src/theme.css.ts

- 앱바에서 툴팁을 띄우는 경우, 앱바 바깥의 UI가 가려지는 이슈
- 개발자가 CSS `overflow` 속성을 제어할 수 있도록 인터페이스 오픈

feat(plugin-basic-ui): add `appBar.overflow` option

---

core/src/activity-utils/findTargetActivityIndexes.ts

공통적으로 사용하는 모듈들을 정의하고 재사용하는데 성공했어요.
PR 이유
- 같은 형태의 코드들의 반복이 있어 하나로 관리할 수 있을 것 같았어요.
- 하나로 관리를 하게되면 나중에 stackflow 유지보수 할 때 편리해질 것으로 예상됩니다!

refactor(core): findTargetActivityIndexes

---

extensions/plugin-history-sync/src/historySyncPlugin.tsx
extensions/plugin-history-sync/src/queue.ts

Delays the next history changing event until the URL sync caused by the previous history event is done.

fix(plugin-history-sync): make history actions work sequentially

---

core/src/produceEffects.spec.ts
core/src/produceEffects.ts

Currently, when a `stepPush` event is invoked, `produceEffects` function causes a bug by producing an unnecessary `REPLACED` effect for all activities entered by the `Replaced` event.
This PR resolves the issue by making the conditions that cause the `REPLACED` effect more demanding.

fix(core): enhance `REPLACED` effect determination

---

docs/pages/advanced/migrate-from-karrotframe.mdx

[문서](https://stackflow.so/advanced/migrate-from-karrotframe#1-stack%EC%9C%BC%EB%A1%9C-%EC%98%AE%EA%B2%A8%EA%B0%80%EA%B8%B0)를 통해 Karrotframe에서 이사를 시도하다 transitionDuration가 누락된 것을 발견하여 문서에 추가했습니다

docs: set transition duration

---

extensions/plugin-google-analytics-4/src/index.ts

```jsx
import { useGoogleAnalyticsContext } from "@stackflow/plugin-google-analytics-4";
const App = () => {
const { setConfig } = useGoogleAnalyticsContext();
useEffect(() => {
setConfig({
user_id: "test123",
user_properties: {
// ...
},
// ...
//  GA4 config values.
// https://bit.ly/3Y7IXhV
});
}, []);
return <div>...</div>;
};
```
위 예제는 plugin의 기본 예제입니다.
해당 예제에서 `useGoogleAnalyticsContext`를 import할 수 없는 상황입니다. 그래서 index.ts에 `useGoogleAnalyticsContext`를 추가시켰습니다.

fix: Add useGoogleAnalyticsContext to export

---

extensions/plugin-history-sync/src/historySyncPlugin.spec.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx

- Add delay time for each test to ensure `exit-done` activity after replaced event
- Add some test to check required specs
- 잘못된 테스트들에 delay 를 추가해서 replace 이벤트 이후 exit-done 이 되어야 하는 activity 들이 exit-done 이 아닌 것을 보정했어요.
- 여전히 문제가 발생하고 있는 시나리오를 테스트로 추가했어요. 또 stepsPush 를 pop 했을 때 정상적으로 pop 해서 stepsPush 를 더 이상 pop 에서 고려하지 않아도 되는 상황을 테스트로 추가했어요.

fix(plugin-history-sync): Implement replacePopCount variable for stepPush when activity is replaced

---

core/src/activity-utils/findTargetActivityIndexes.ts
core/src/aggregate.spec.ts

- Add test for issue that pop event is activated although current stack is root stack by replace event.
- replace 이벤트로 인해 root 스택에 있는 경우, pop 이벤트를 수행하면 pop 이 진행되지 않아야 하는데, 이것을 확인하는 테스트를 추가합니다.
- Fix 추가

fix(core): prevent replaced root activity from pop event

---

extensions/plugin-google-analytics-4/src/googleAnalyticsPlugin.tsx
extensions/plugin-history-sync/src/historySyncPlugin.tsx
extensions/plugin-preload/src/pluginPreload.tsx
integrations/react/src/StackflowReactPlugin.ts
integrations/react/src/shims/useSyncExternalStore.ts
integrations/react/src/stackflow.tsx
integrations/react/src/useActions.ts
integrations/react/src/utils/useMemoDeep.ts

좋은 라이브러리를 공유해주셔서 감사합니다. 🙇‍♂️
저는 코드 일부를 리팩토링 작업을 진행했습니다.
적절한 Pull Request 인지 검토해주시면 감사드립니다!

refactor(stackflow): Refactoring stackflow

---

core/src/utils/id.spec.ts
core/src/utils/time.spec.ts

안녕하세요 👋
core/utils 내부의 `id()`와 `time()` 함수에 대한 테스트 코드를 추가하는 작업을 진행해봤습니다.
적절한 Pull Request인지 검토부탁드립니다 🙏
jest에서 제공해주는 `useFakeTimer()`를 통해 파일 내의 테스트에 가짜 타이머를 적용 후, `setSystemTime()`을 통해 현재 시스템 시간을 설정해 `time()` 함수와 이에 의존하는 `id()` 함수의 테스트 코드를 작성하였습니다.
[jest - useFakeTimers](https://jestjs.io/docs/jest-object#jestusefaketimersfaketimersconfig)
[jest - setSystemTime](https://jestjs.io/docs/jest-object#jestsetsystemtimenow-number--date)

test(stackflow): Add id/time Test Code

---

extensions/link/src/Link.tsx

`<Link />` anchorProps에서 `replace`를 제거해요.
- 기존에는 a tag에 `replace=boolean` attribute가 포함되어 브라우저에서 아래와 같은 워닝 메세지가 뜨고 있었어요
```text
Warning: Received `true` for a non-boolean attribute `replace`.
If you want to write it to the DOM, pass a string instead: replace="true" or replace={value.toString()}.
```
- anchorProps에서 `replace` 를 제거해서 a tag에 내려주지 않게 만들었어요.
- replace를 string으로 치환해서 내려주는 방법도 있어요.
- replace는 현재 stackflow 내부 동작에만 관여하는 props라서 제거를 선택했어요.

fix(link): remove `replace` from anchorProps

---

extensions/plugin-basic-ui/src/hooks/useMaxWidth.ts

For now, `max-width` of centered component cannot be changed while the size of some components out of that in `AppBar` is changed by re-rendering (e.g. conditional rendering)
This PR fixes the issue by invoking effect regardless of dependencies for the effect.

fix(plugin-basic-ui): remove deps array from max width effect

---

extensions/plugin-google-analytics-4/src/googleAnalyticsPlugin.tsx
extensions/plugin-google-analytics-4/src/index.ts
extensions/plugin-history-sync/src/historySyncPlugin.tsx
extensions/plugin-preload/src/pluginPreload.tsx
integrations/react/src/StackflowReactPlugin.ts
integrations/react/src/stackflow.tsx

If the `activities` type is not received through return generic `T`, the following problem occurs where type inference is not performed properly.
Since the `activities` type is normally received through generic `T`, the type can be inferred normally.

fix: rollback to `StackflowReactPlugin<T = never>`

---

extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppBar.tsx
extensions/plugin-basic-ui/src/components/AppScreen.css.ts
extensions/plugin-basic-ui/src/components/AppScreen.tsx
extensions/plugin-basic-ui/src/hooks/useStyleEffectOffset.ts
packages/eslint-config/index.js

- Implement `slideInLeft` transition on `android` theme
https://github.com/daangn/stackflow/assets/20325202/db61bc1e-3ac3-4881-8a18-76412791a67b
- Refactoring
- Rename `<AppScreen />` props `modalPresentationStyle` -> `CUPERTINO_ONLY_modalPresentationStyle`

feat(plugin-basic-ui): `ANDROID_ONLY_activityEnterStyle`

---

.changeset/dull-eyes-love.md
.changeset/pre.json
demo/CHANGELOG.md
demo/package.json
docs/CHANGELOG.md
docs/package.json
extensions/plugin-stack-depth-change/CHANGELOG.md
extensions/plugin-stack-depth-change/package.json
extensions/plugin-stack-depth-change/src/stackDepthChangePlugin.tsx
yarn.lock

For now, `stackDepthChangePlugin` invokes `onDepthChanged` callback whenever `onChanged` hook is called.
Our organization has decided to invoke that callback only when the depth level has changed by some internal requests.
And also, that's what we expect from the name in the plugin.

feat(plugin-stack-depth-change): invoke callback only when depth level has changed

---

.changeset/rotten-berries-sort.md
extensions/plugin-history-sync/src/HistoryQueueContext.tsx
extensions/plugin-history-sync/src/historySyncPlugin.tsx
extensions/plugin-history-sync/src/queue.ts

- fix(plugin-history-sync)!: reduce loop count for parsing state
**BREAKING CHANGES:**
- Replace `listen` option into `resolve()` parameter for `requestHistoryTick()`

fix(plugin-history-sync)!: reduce loop count for parsing state

---

.changeset/weak-jobs-whisper.md
extensions/plugin-basic-ui/src/basicUIPlugin.css.ts

- Theme dependency is currently required for pre-rendering the app shell to HTML.
- Since the theme cannot be imported through JavaScript, it must be adjustable through the `:root` property.
- Therefore, re-add the global theme deleted from https://github.com/daangn/stackflow/pull/370.

fix(plugin-basic-ui): theme branching via `:root`'s dataset

---

docs/theme.config.jsx

In the current stackflow docs built with Nextra, clicking the ***Edit this page*** button moves to the [Not Found](https://github.com/daangn/stackflow/pages/index.mdx) page.
According to the [Nextra docs](https://nextra.site/docs/docs-theme/theme-configuration#specify-a-path), when using a monorepo, it is necessary to set up a separate base, so I modified `docsRepositoryBase` property in theme.config.jsx
Before
After

fix(docs): update docsRepositoryBase

---

.changeset/green-bulldogs-learn.md
core/src/event-utils/makeEvent.ts
extensions/plugin-history-sync/src/historyState.ts

- I discovered the possibility of passing an object with circular dependency to `activity.context`, so there was logic to delete the `activity.context` to make it serializable before assigning it to `history.state`.
- There was a case where `activity.context` was utilized in user land. In this case, the stability of the `activity.context` field must be guaranteed.
- After thinking about it further, I realized that **the event** itself is **serializable**, so I changed the `makeEvent()` function to check for serializability and deleted the logic to delete the `activity.context`.

fix(core, plugin-history-sync): accept only serializable parameters

---

.changeset/funny-kings-attack.md
.changeset/gentle-kangaroos-study.md
.changeset/pre.json
demo/CHANGELOG.md
demo/package.json
docs/CHANGELOG.md
docs/package.json
extensions/plugin-basic-ui/src/components/AppScreen.tsx
extensions/plugin-basic-ui/src/components/BottomSheet.tsx
extensions/plugin-basic-ui/src/components/Modal.tsx
extensions/plugin-basic-ui/src/hooks/index.ts
extensions/plugin-basic-ui/src/hooks/useZIndexBase.ts
extensions/plugin-basic-ui/src/index.ts
yarn.lock

Export `useStyleEffect()`, `useZIndexBase()` hooks to extend the basic ui based custom activities for the third parties.

feat(plugin-basic-ui): export `useStyleEffect()`, `useZIndexBase()`

---

.changeset/short-jars-retire.md
demo/src/activities/Main.css.ts
extensions/plugin-basic-ui/src/components/AppScreen.css.ts

- Substract the height of `AppBar` from `AppScreen` and apply top margin instead of top padding so that paper could have the visible height itself.

style(plugin-basic-ui): move top padding to margin

---

.changeset/ten-squids-yell.md
extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppScreen.css.ts
extensions/plugin-basic-ui/src/components/BottomSheet.css.ts
extensions/plugin-basic-ui/src/components/Modal.css.ts

Currently, the element that has `will-change` property will generate the containing block for the nested fixed element. [W3C Spec](https://drafts.csswg.org/css-will-change/)
To reduce the confusion of using the `position: fixed` element inside `AppScreen` and the other utility activities, we decided to remove the all `will-change` properties used in them.

fix(plugin-basic-ui): remove `will-change` property

---

.changeset/lazy-months-repair.md
tsconfig.json

Opt-in `declarationMap` for ease in finding the original source within the monorepo or the external uses.

chore: enable `declarationMap` compiler option

---

.changeset/tasty-penguins-grow.md
extensions/plugin-history-sync/src/sortActivityRoutes.spec.ts
extensions/plugin-history-sync/src/sortActivityRoutes.ts

Reference: https://github.com/remix-run/react-router/blob/0f2b167e9b862d5e6b3425438787c8e7b39197f4/packages/router/utils.ts#L742-L773

feat(plugin-history-sync): sort routes by computed score

---

.changeset/tough-cycles-reflect.md
extensions/plugin-basic-ui/src/components/AppScreen.css.ts

Fixes a bug introduced by #479 which results in height larger than the actual screen when the device has safe-area-inset-top value other than 0.

fix(plugin-basic-ui): calculate app screen height correctly with safearea

---

.changeset/chilled-items-protect.md
extensions/plugin-basic-ui/src/components/AppScreen.tsx

AppScreen 및 관련 요소들은 z-index를 사용해 스택형 UI를 구현하고 있습니다.
현재 인터페이스에서는 Popover와 같은 floating 요소를 제어할 때 "AppScreen보다 높아야 하지만, AppBar에는 가려져야 한다." 와 같은 요구사항을 해결하기 어려운 문제가 있습니다.
따라서, `useAppScreen()`에 `zIndices` 정보를 추가해 하위 컴포넌트에서 `zIndex: zIndices.appBar - 1` 과 같이 사용할 수 있도록 합니다.

feat(plugin-basic-ui): add interface to access z-index about AppScreen

---

docs/CHANGELOG.md
docs/components/index-page/Tile.tsx
docs/components/index-page/index.tsx
docs/package.json

This pull request fixes the styles in the mobile view.
The changes include fixing the width of a container and adding padding to a paragraph element.

fix(docs): styles in mobile view

---

docs/pages/api-references/future-api/api-pipelining.en.mdx
docs/pages/api-references/future-api/api-pipelining.ko.mdx

This pull request includes changes to improve type safety by replacing the `any` type with `unknown` in the `initialLoaderData` variable and function parameter in two documentation files.
Type safety improvements:
* [`docs/pages/api-references/future-api/api-pipelining.en.mdx`](diffhunk://#diff-fbfcab5142ca63b4e19db4e90a7d831c8aded2126f948f39c3389a0c4775d667L14-R14): Changed the type of `initialLoaderData` from `any` to `unknown` in the `main` function and `renderApp` function parameter. [[1]](diffhunk://#diff-fbfcab5142ca63b4e19db4e90a7d831c8aded2126f948f39c3389a0c4775d667L14-R14) [[2]](diffhunk://#diff-fbfcab5142ca63b4e19db4e90a7d831c8aded2126f948f39c3389a0c4775d667L41-R41)
* [`docs/pages/api-references/future-api/api-pipelining.ko.mdx`](diffhunk://#diff-94858f2ae2c62df3abefbfa3fb235c046 …

docs: change `initialLoaderData` type to use `unknown` instead of `any`

---

docs/pages/docs/get-started/navigating-activities.en.mdx

The current documentation for the pop() function does not fully explain its functionality. While it mentions additional options as the first parameter, the implementation shows that the first parameter can also be a number specifying the number of stacks to pop. This PR updates the documentation to accurately reflect the function’s behavior.
---
1. Clarified the pop() function’s parameters:
- Added details about the count parameter for specifying the number of stacks to pop.
- Explained the dual usage of the first parameter (as a number or options object).
2. Updated code examples to demonstrate:
- Popping multiple stacks.
- Combining count and options parameters.
3. Enhanced the parameter table with default values and examples.

Supplement Documentation for pop() Function

---

.changeset/four-colts-nail.md
core/src/makeCoreStore.ts
core/src/utils/divideBy.ts

Current type definition of `divideBy` has loose typing that makes programmer to use unnecessary assertions or additional checks. I've changed the type so that we can remove uncomfortable assertions.
- Since there is no 'negated type' in typescript, Unsatisfied cases remains to be value of the type `T`. ([`Exclude` is not an option](https://github.com/microsoft/TypeScript/wiki/FAQ#exclude-isnt-type-negation))
- `divideBy`'s being parameterized by two unrelated types was considered but eventually excluded since it does not work well with the type checker's design. (Due to subtyping, it is possible for the type checker to infer an variable as too general type)

chore(stackflow/core): Type inference friendly `divideBy`

---

.changeset/plenty-stingrays-knock.md
integrations/react/src/__internal__/activity/findLatestActiveActivity.ts
integrations/react/src/future/StepActions.ts
integrations/react/src/future/makeStepActions.ts
integrations/react/src/future/stackflow.tsx
integrations/react/src/future/useStepFlow.ts
integrations/react/src/stable/stackflow.tsx
integrations/react/src/stable/useStepActions.ts

As current implementation resolves target activity of a given step creation event(push or replace) to latest active activity(lastly entered activity), update functions are given up-to-date params of them.

feat(react): make 'the update function pattern' available in step creation(push/replace)

---

.changeset/poor-mice-join.md
extensions/plugin-basic-ui/src/basicUIPlugin.css.ts
extensions/plugin-basic-ui/src/basicUIPlugin.tsx
extensions/plugin-basic-ui/src/components/AppBar.css.ts
extensions/plugin-basic-ui/src/components/AppBar.tsx
extensions/plugin-basic-ui/src/components/AppScreen.css.ts
extensions/plugin-basic-ui/src/components/AppScreen.tsx
extensions/plugin-basic-ui/src/components/BottomSheet.css.ts
extensions/plugin-basic-ui/src/components/BottomSheet.tsx
extensions/plugin-basic-ui/src/components/Modal.css.ts
extensions/plugin-basic-ui/src/components/Modal.tsx

To support various background designs, enable users to configure the `background-image` option in `AppScreen`, `AppBar`, `BottomSheet` and `Modal`.

feat(plugin-basic-ui): Add option to configure `background-image`

---

.changeset/metal-pandas-dance.md
extensions/plugin-basic-ui/src/basicUIPlugin.css.ts
extensions/plugin-basic-ui/src/basicUIPlugin.tsx
extensions/plugin-basic-ui/src/components/AppScreen.tsx
extensions/react-ui-core/src/index.ts
extensions/react-ui-core/src/usePreventTouchDuringTransition.ts
extensions/react-ui-core/src/usePreventTouchEvents.ts

In iOS Safari, there is a behavior that the scroll target is focused to the initially touched element until the scroll momentum ends, even if the target element is unmounted or the momentum itself is initially zero.
This behavior can be a problematic when `pointer-events: none;` property is set to stack wrapper element because the scrolling is attempted on an unintended target (usually a document element) and the continuous reviving of the momentum by touches can be keeping the `AppScreen` unscrollable forever.
Therefore, a handler has been added to the `AppScreen` component to prevent `touchstart` events instead using the `pointer-events: none;` style property for the original purpose of preventing the user-side action during transitions.

fix(plugin-basic-ui,react-ui-core): prevent touch events while transitioning
